prj:
  name: back-normal
  version: v0.0.1
  id: 123

port: 80

log.root: /web/logs

mysql:
  user: user
  password: password
  address: localhost:3306
  db: testdb
  conns:
    maxOpen: 40
    maxIdle: 2
    timeout: 500ms
    readTimeout: 3s

type:
  int: -5
  float32: 6.6
  float64: 8.8
  int8: -8
  int16: -16
  int32: -32
  int64: -64
  uint: 5
  uint8: 8
  uint16: 16
  uint32: 32
  uint64: 64




